########################################################
## the configure data for models
########################################################

# the configure info for datasets
dataset:
    train_path: ./datas/train/train_data.txt
    test_path: ./datas/test/test_data.txt
    label_name: click
    type: csv
    params:
        header: 0
        sep: ','

# the configure info for feature columns
columns:
    id: float
    click: int
    hour: float
    C1: float
    banner_pos: float
    site_id: string
    site_domain: string
    site_category: string
    app_id: string
    app_domain: string
    app_category: string
    device_id: string
    device_ip: string
    device_model: string
    device_type: float
    device_conn_type: float
    C14: float
    C15: float
    C16: float
    C17: float
    C18: float
    C19: float
    C20: float
    C21: float

# the configure info for model
model:
    num_episodes: 500
    num_exploration_episodes: 100
    max_len_episode: 1000
    seq_length: 40
    batch_size: 32
    learning_rate: 0.001
    gamma: 1.0
    initial_epsilon: 1.0
    final_epsilon: 0.01
    optimizer: Adam
    classes: 2
    deep:
        units: [24, 24]
        activation: relu

    wide:
        activation: sigmoid