########################################################
## the configure data for models
########################################################

# the configure info for datasets
dataset:
    train_path: D:/project/DeepCTR-tf2/datas/train/train_data.txt
    test_path: ./datas/test/test_data.txt
    label_name: label
    type: csv
    batch_size: 32
    epoches: 10
    params:
        header: True
        sep: ','
    schema:
        id:
            type: string
            default: '0'
        label:
            type: int
        hour:
            type: string
            default: '14102100'
        C1:
            type: string
            default: '1005'
        banner_pos:
            type: int
            default: 0
        site_id:
            type: string
            default: '0'
        site_domain:
            type: string
            default: '0'
        site_category:
            type: string
            default: '0'
        app_id:
            type: string
            default: '0'
        app_domain:
            type: string
            default: '0'
        app_category:
            type: string
            default: '0'
        device_id:
            type: string
            default: '0'
        device_ip:
            type: string
            default: '0'
        device_model:
            type: string
            default: '0'
        device_type:
            type: string
            default: '0'
        device_conn_type:
            type: string
            default: '0'
        C14:
            type: string
            default: '0'
        C15:
            type: string
            default: '0'
        C16:
            type: string
            default: '0'
        C17:
            type: string
            default: '0'
        C18:
            type: string
            default: '0'
        C19:
            type: string
            default: '0'
        C20:
            type: string
            default: '0'
        C21:
            type: string
            default: '0'

# the configure info for model
model:
    num_episodes: 500
    num_exploration_episodes: 100
    max_len_episode: 1000
    seq_length: 40
    batch_size: 32
    learning_rate: 0.001
    gamma: 1.0
    initial_epsilon: 1.0
    final_epsilon: 0.01
    optimizer: Adam
    classes: 2
    deep:
        units: [24, 24]
        activation: relu

    wide:
        activation: sigmoid