########################################################
## the configure data for models
########################################################

model:
    num_epoches: 15
    batch_size: 128
    learning_rate: 0.001
    optimizer: Adam
    classes: 10
    deep:
        units: [100]
        activation: relu

    wide:
        activation: softmax