########################################################
## the configure data for models
########################################################

# the configure info for datasets
dataset:
    train_path: ../../examples/datas/train.txt
    test_path: ./datas/test
    type: csv
    batch_size: 4
    epoches: 1
    params:
        header: True
        sep: '\t'

# the configure info for model
model:
    batch_size: 32
    classes: 2
    deep:
        units: [24, 24]
        activation: relu

    wide:
        activation: sigmoid

# the configure info for training processing
train:
    optimizer: Adagrad
    optimizer_params:
        learning_rate: 0.005
        initial_accumulator_value: 0.1
        epsilon: 1e-07
    loss: reduce_sum_sparse_categorical_crossentropy

run:
    epoches: 20
    train_steps: 10000
    loss_steps: 5000
    eval_steps: 2000