########################################################
## the configure data for models
########################################################

# the configure info for datasets
dataset:
    train_path: ../../examples/datas/train.txt
    test_path: ./datas/test
    type: csv
    batch_size: 4
    epoches: 1
    params:
        header: True
        sep: '\t'

# the configure info for model
model:
    num_episodes: 500
    num_exploration_episodes: 100
    max_len_episode: 1000
    seq_length: 40
    batch_size: 32
    learning_rate: 0.001
    gamma: 1.0
    initial_epsilon: 1.0
    final_epsilon: 0.01
    optimizer: Adam
    classes: 2
    deep:
        units: [24, 24]
        activation: relu

    wide:
        activation: sigmoid